/** Screen 5 — Recipes generated by AI from your scanned fridge ingredients. */
import AsyncStorage from '@react-native-async-storage/async-storage';
import { router } from 'expo-router';
import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { H } from '@/components/Headline';
import { Icon } from '@/components/Icon';
import { PrimaryButton } from '@/components/PrimaryButton';
import { RecipeCard } from '@/components/RecipeCard';
import { ScreenBg } from '@/components/ScreenBg';
import { Txt } from '@/components/Txt';
import { useAuth } from '@/lib/auth';
import { useFridgeItems } from '@/lib/fridge';
import { useNav } from '@/lib/nav';
import { useProfileRow } from '@/lib/profile';
import {
  generateRecipes,
  setActiveRecipe,
  useSavedRecipes,
  viewFromGenerated,
  type GeneratedRecipe,
} from '@/lib/recipes';
import { useTheme } from '@/theme/ThemeProvider';

function strList(row: unknown, local: unknown): string[] {
  if (Array.isArray(row)) return row as string[];
  if (Array.isArray(local)) return local as string[];
  return [];
}

export default function RecipesScreen() {
  const { theme } = useTheme();
  const insets = useSafeAreaInsets();
  const nav = useNav();

  const { items } = useFridgeItems();
  const { row, local } = useProfileRow();
  const { session } = useAuth();
  const saved = useSavedRecipes();

  const ingredients = items.map((i) => i.name);
  const dietaryStyles = strList(row?.dietary_styles, local.dietaryStyles);
  const allergies = strList(row?.allergies, local.allergies);
  const goal = row?.goal ?? (typeof local.goal === 'string' ? local.goal : undefined);

  const [generated, setGenerated] = useState<GeneratedRecipe[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // the fridge signature we last kicked off generation for — guards against
  // re-running for the same fridge (incl. React strict-mode double effects)
  const ranSig = useRef<string | null>(null);

  const openRecipe = (r: GeneratedRecipe) => {
    setActiveRecipe(viewFromGenerated(r));
    router.push('/recipe');
  };

  // signature of everything that shapes generation — the fridge contents AND the
  // user's diet, allergies, and goal. Cached results are reused only while ALL of
  // these are unchanged, so adding an allergy (or changing diet/goal) regenerates
  // instead of serving stale, possibly-unsafe recipes for the new constraints.
  const normList = (xs: string[]) => xs.map((s) => s.toLowerCase().trim()).filter(Boolean).sort().join(',');
  const sig = [
    normList(ingredients),
    normList(dietaryStyles),
    normList(allergies),
    (goal ?? '').toLowerCase().trim(),
  ].join('||');
  // per-user cache key so two accounts on one device can't read each other's recipes
  const CACHE_KEY = `recipeCache:${session?.user?.id ?? 'anon'}`;

  const run = async (forceFresh: boolean) => {
    if (ingredients.length === 0) return;
    if (!forceFresh) {
      try {
        const raw = await AsyncStorage.getItem(CACHE_KEY);
        if (raw) {
          const cached = JSON.parse(raw) as { sig: string; recipes: GeneratedRecipe[] };
          if (cached.sig === sig && Array.isArray(cached.recipes) && cached.recipes.length) {
            setGenerated(cached.recipes);
            return; // hit — no API call, no spend
          }
        }
      } catch {
        /* ignore cache miss */
      }
    }
    setLoading(true);
    setError(null);
    try {
      const recipes = await generateRecipes({ ingredients, dietaryStyles, allergies, goal, count: 4 });
      setGenerated(recipes);
      AsyncStorage.setItem(CACHE_KEY, JSON.stringify({ sig, recipes })).catch(() => {});
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not generate recipes.');
    } finally {
      setLoading(false);
    }
  };

  // Generate whenever the fridge contents change. run(false) reuses the cache
  // when the signature already has results, so an unchanged fridge costs nothing
  // and only a genuinely new fridge triggers a fresh (paid) generation.
  useEffect(() => {
    if (ingredients.length === 0 || ranSig.current === sig) return;
    ranSig.current = sig;
    run(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sig]);

  const regenerate = () => {
    run(true);
  };

  return (
    <ScreenBg>
      <ScrollView
        contentContainerStyle={{ paddingTop: insets.top + 10, paddingBottom: 28 }}
        showsVerticalScrollIndicator={false}
      >
        <View style={{ flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', paddingHorizontal: 22 }}>
          <View style={{ flex: 1 }}>
            <H size={32} style={{ letterSpacing: -0.3 }}>
              Recipes
            </H>
            <Txt w={500} size={14.5} color={theme.inkSec} style={{ marginTop: 8 }}>
              {ingredients.length > 0
                ? `From the ${ingredients.length} ingredient${ingredients.length > 1 ? 's' : ''} in your fridge.`
                : 'Scan your fridge to get recipe ideas.'}
            </Txt>
          </View>
          <View style={{ flexDirection: 'row', gap: 8, marginTop: 6 }}>
            <Pressable
              onPress={() => nav.go('fridge')}
              accessibilityRole="button"
              accessibilityLabel="My fridge"
              style={{
                width: 42,
                height: 42,
                borderRadius: 21,
                backgroundColor: theme.surface,
                borderWidth: 1.5,
                borderColor: theme.border,
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <Icon name="fridge" size={19} color={theme.primary} stroke={1.7} />
            </Pressable>
            {ingredients.length > 0 && (
              <Pressable
                onPress={regenerate}
                disabled={loading}
                accessibilityRole="button"
                accessibilityLabel="Regenerate recipes"
                accessibilityState={{ disabled: loading }}
                style={{
                  width: 42,
                  height: 42,
                  borderRadius: 21,
                  backgroundColor: theme.surface,
                  borderWidth: 1.5,
                  borderColor: theme.border,
                  alignItems: 'center',
                  justifyContent: 'center',
                  opacity: loading ? 0.5 : 1,
                }}
              >
                <Icon name="sparkle" size={19} color={theme.primary} stroke={1.7} />
              </Pressable>
            )}
          </View>
        </View>

        {/* empty fridge */}
        {ingredients.length === 0 && (
          <View style={{ marginHorizontal: 22, marginTop: 24, alignItems: 'center' }}>
            <View
              style={{
                width: 72,
                height: 72,
                borderRadius: 22,
                backgroundColor: theme.primarySoft,
                alignItems: 'center',
                justifyContent: 'center',
                marginBottom: 18,
              }}
            >
              <Icon name="fridge" size={32} color={theme.primary} stroke={1.7} />
            </View>
            <H size={21} style={{ textAlign: 'center' }}>
              Your fridge is empty
            </H>
            <Txt w={500} size={14.5} color={theme.inkSec} style={{ textAlign: 'center', marginTop: 8, marginBottom: 22, lineHeight: 21 }}>
              Scan what you have and we&apos;ll suggest recipes you can cook right now.
            </Txt>
            <View style={{ width: '100%' }}>
              <PrimaryButton onPress={() => nav.go('scan')}>Scan your fridge</PrimaryButton>
            </View>
          </View>
        )}

        {/* loading */}
        {ingredients.length > 0 && loading && (
          <View style={{ alignItems: 'center', marginTop: 40 }}>
            <ActivityIndicator color={theme.primary} />
            <Txt w={600} size={14} color={theme.inkSec} style={{ marginTop: 14 }}>
              Cooking up ideas from your fridge…
            </Txt>
          </View>
        )}

        {/* error */}
        {ingredients.length > 0 && !loading && error && (
          <View style={{ marginHorizontal: 22, marginTop: 28, alignItems: 'center' }}>
            <Txt w={600} size={14} color={theme.protein} style={{ textAlign: 'center', marginBottom: 16, lineHeight: 20 }}>
              {error}
            </Txt>
            <View style={{ width: '100%' }}>
              <PrimaryButton onPress={regenerate}>Try again</PrimaryButton>
            </View>
          </View>
        )}

        {/* results */}
        {ingredients.length > 0 && !loading && !error && generated.length > 0 && (
          <>
            <View
              style={{
                marginHorizontal: 22,
                marginTop: 18,
                padding: 16,
                borderRadius: 16,
                backgroundColor: theme.primarySoft,
                flexDirection: 'row',
                alignItems: 'center',
                gap: 12,
              }}
            >
              <View
                style={{
                  width: 40,
                  height: 40,
                  borderRadius: 12,
                  backgroundColor: theme.primary,
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <Icon name="sparkle" size={22} color={theme.onPrimary} stroke={1.7} fill={theme.onPrimary} />
              </View>
              <Txt w={600} size={13.5} color={theme.ink} style={{ flex: 1, lineHeight: 18 }}>
                <Txt w={800} size={13.5} color={theme.ink}>
                  {generated.length} recipes
                </Txt>{' '}
                tailored to what you have{allergies.length ? ' — allergy-aware' : ''}.
              </Txt>
            </View>

            <View style={{ paddingHorizontal: 22, paddingTop: 18, gap: 12 }}>
              {generated.map((r) => (
                <RecipeCard
                  key={r.title}
                  recipe={viewFromGenerated(r)}
                  saved={saved.isSaved(r.title)}
                  onPress={() => openRecipe(r)}
                  onSave={() => (saved.isSaved(r.title) ? saved.remove(r.title) : saved.save(r))}
                />
              ))}
            </View>

            <Txt
              w={500}
              size={12}
              color={theme.inkSec}
              style={{ paddingHorizontal: 30, paddingTop: 18, textAlign: 'center', lineHeight: 17 }}
            >
              Recipes and nutrition are AI-generated estimates. Always check ingredients for allergens
              before cooking.
            </Txt>
          </>
        )}
      </ScrollView>
    </ScreenBg>
  );
}
